apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret   # K8s 내에서 이 Secret을 부를 이름
type: Opaque
data:
  # key: postgres-password
  # value: '비밀번호'를 base64로 인코딩한 값
  postgres-password: MTIzNA==
