apiVersion: v1
kind: Service
metadata:
  name: postgres-service   # K8s 내에서 이 Service(DB 접속 주소)의 이름
spec:
  type: ClusterIP          # 클러스터 내부에서만 접근 가능
  selector:
    app: postgres          # 'app: postgres' 라벨이 붙은 Pod을 찾아 연결
  ports:
    - protocol: TCP
      port: 5432           # Service가 노출하는 포트
      targetPort: 5432     # Pod 내부 컨테이너 포트
