apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  # DB 접속 정보
  POSTGRES_HOST: "postgres-service"   # 05-db-service.yaml에서 만든 Service 이름
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_PORT: "5432"

  # Django 설정
  DJANGO_DEBUG: "False"               # 운영 환경에서는 반드시 False
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,192.168.56.11,board.k8s.local"           # 테스트용으로 모두 허용 (운영에서는 도메인만 지정)
